spring:
  application:
    name: peektime-admin
  sql:
    init:
      mode: never
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true
    encoding: UTF-8
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: when_authorized
  prometheus:
    metrics:
      export:
        enabled: true