# 운영 환경 (MySQL)
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

admin:
  base-url: ${PROD_ADMIN_BASE_URL}

firebase:
  credentials: ${FIREBASE_CREDENTIALS}