spring:
  application:
    name: peektime-api
  profiles:
    active: local
  jpa:
    open-in-view: false

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region: ap-northeast-2
