spring:
  application:
    name: peaktime-api
  profiles:
    active: local
  jpa:
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging:
  level:
    org.springframework.web: DEBUG
    com.team.peektime_api: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:2592000000}

admin:
  base-url: ${ADMIN_BASE_URL:http://localhost:8081}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region: ap-northeast-2

firebase:
  credentials-path: classpath:firebase/firebase-service-account.json
